apiVersion: v1
kind: Service
metadata:
  name: ethereumnode-poa-b
  namespace: poa
spec:
  type: NodePort
  ports:
    - port: 8647
      targetPort: 8545
      protocol: TCP
      name: jsonrpc
    - port: 8648
      targetPort: 8546
      protocol: TCP
      name: ws
    - port: 31304
      targetPort: 30303
      protocol: TCP
      name: network
    - port: 31304
      targetPort: 30303
      protocol: UDP
      name: networksync
  selector:
    app: ethereumnode-poa-b
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ethereumnode-poa-b
  namespace: poa
spec:
  replicas: 1
  # securityContext:
  #   runAsUser: 1000
  #   fsGroup: 1000
  template:
    metadata:
      labels:
        app: ethereumnode-poa-b
    spec:
      containers:
        - image: "vincentserpoul/paritypoa:v2.2.2"
          name: ethereumnode-poa-b
          env:
            - name: JSONRPC_PORT
              value: "8545"
            - name: WS_PORT
              value: "8546"
            - name: NETWORK_PORT
              value: "30303"
          ports:
            - containerPort: 8545
              name: jsonrpc
            - containerPort: 8546
              name: ws
            - containerPort: 30303
              name: network
          volumeMounts:
            - name: ethblockchain-b
              mountPath: "/home/parity/.local/share/io.parity.ethereum"
            - name: poaconfigs
              mountPath: /home/parity/.poaconfigs
            - name: poasecrets
              mountPath: /home/parity/.poasecrets
      volumes:
        - name: ethblockchain-b
          emptyDir: null
        - name: poaconfigs
          configMap:
            name: poaconfigs-b
        - name: poasecrets
          secret:
            secretName: poasecrets-b
# kubectl apply -f ./kubernetes/b.yaml
